### PR TITLE
Accommodate change of empty vector representation in nightly libstd.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/heapsize/81)

### CODE REVIEW

**Comment by jrmuizel** [comment]
What was the number of the change in libstd?

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/41064

**Comment by SimonSapin** [comment]
Specifically the changes to `src/liballoc/heap.rs` in that PR. (So it affects all zero-size heap "allocations", not just Vec.)

**Pull request merged**
