### PR TITLE
Support arrays

### PR DESCRIPTION
**Pull request by Manishearth**
r? @nox

---

This change is [Reviewable](https://reviewable.io/reviews/servo/heapsize/55)

### CODE REVIEW

**Comment by nox** [comment]
Could we refactor it to handle combinations of arrays of tuples and of tuples of arrays?

**Comment by Manishearth** [comment]
Yes, we just need to make the contents of fold into a separate, recursive function `fold_field(ty: &Ty, field: &FieldInfo, accum: &mut Expr)`.

**Comment by nox** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[plugin/src/heap_size.rs, line 75 \[r1\]](https://reviewable.io:443/reviews/servo/heapsize/55#-KDytcuoTDPUkwunMBvE:-KDytcuoTDPUkwunMBvF:-1334266723) ([raw file](https://github.com/servo/heapsize/blob/cbc65209c6746db228c8b48a33d612ce4f581cb6/plugin/src/heap_size.rs#L75)):*
This would be more readable if we did a short-circuting return when `has_ignore` is true.

---

*[plugin/src/heap_size.rs, line 93 \[r1\]](https://reviewable.io:443/reviews/servo/heapsize/55#-KDytnBIFLcGlJ1wmZ4y:-KDytnBIFLcGlJ1wmZ4z:666181885) ([raw file](https://github.com/servo/heapsize/blob/cbc65209c6746db228c8b48a33d612ce4f581cb6/plugin/src/heap_size.rs#L93)):*
Wrong indentation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/heapsize/55)*

**Comment by nox** [comment]
Squash and r=me.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/heapsize/55#-:-KEfvC2tVH3bEE3fG9Zu:456151462)*

**Comment by nox** [comment]
@Manishearth Ping?

**Comment by Manishearth** [comment]
Needs re-review for rustup (small change)

**Comment by nox** [comment]
Please squash and r=me.

<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary>
> Needs re-review for rustup (small change)
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/heapsize/55#-:-KJbSYDnaw0keHd9oktp:-1970385614)*

**Comment by nox** [comment]
@Manishearth Think you could port that to heapsize_derive?

**Comment by Manishearth** [comment]
Probably should let @SimonSapin do that; I'm not yet well read up on syn.

**Comment by SimonSapin** [comment]
https://github.com/servo/heapsize/pull/66

**Pull request closed without merging**
