### PR TITLE
Add the compiler plugin

### LINKED ISSUE #2: Does the compiler plugin go in here?
Exactly that question. Should we move `components/plugins/heap_size.rs` (and it's entry in `components/plugins/lib.rs`) into here as well?

### PR DESCRIPTION
**Pull request by notriddle**
Closes #2.

### CODE REVIEW

**Comment by notriddle** [comment]
Is there any way to have Travis CI build the plugin, too?

**Comment by jdm** [comment]
We could make heapsize depend on heapsize_plugin.

**Comment by jdm** [comment]
See html5ever for an example: https://github.com/servo/string-cache/blob/master/Cargo.toml#L38

**Comment by SimonSapin** [comment]
Don’t add a dependency just to have Travis-CI build the plugin. Rather, run multiple commands in the `script` section of `.travis.yml`: https://github.com/servo/string-cache/blob/18ac6e1ec9/.travis.yml#L11-L12

**Comment by Manishearth** [comment]
You'll need to fill out the Cargo.toml with more information so that this can be published (see https://github.com/servo/heapsize/pull/8/files)

**Comment by notriddle** [comment]
I've done it.

**Pull request merged**
