### PR TITLE
Fix build script when the rustc commit date is unknown.

### PR DESCRIPTION
**Pull request by SimonSapin**
Hopefully fixes https://github.com/servo/heapsize/pull/44#issuecomment-187935883.

[Review on Reviewable](https://reviewable.io/reviews/servo/heapsize/49)

### CODE REVIEW

**Comment by SimonSapin** [comment]
When building Rust from a source tarball, the commit date is `unknown`. This PR makes the build script support that case. I’ve tried it locally with https://static.rust-lang.org/dist/rustc-nightly-src.tar.gz

Ideally we’d have CI for this, but I’m not aware of binary builds with commit date `unkown`, and building Rust on Travis for every heapsize change would be prohibitively slow.

r? @nox

**Comment by petevine** [comment]
Hey, still not merged? This change is important as the officially distributed rust source comes in a tarball:
https://www.rust-lang.org/downloads.html

**Comment by larsbergstrom** [comment]
@bors-servo r+

CC'ing @alexcrichton since this seems like the kind of madness he'd be interested in knowing about :-)

**Comment by SimonSapin** [comment]
@petevine Sorry for the delay! I’ve just published v0.3.4 with this change on crates.io.

**Comment by petevine** [comment]
Thanks!

**Pull request merged**
